config/routes.rb
Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?
  post '/graphql', to: 'graphql#execute'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :front do
    root to: 'top#index'

    get :vf_rank, to: 'vf_rank#index'
  end

  namespace :admin do
    root to: 'top#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mid_music_music_genre.rb
class MidMusicMusicGenre < ApplicationRecord
  belongs_to :mst_music
  belongs_to :mst_music_genre
end

app/models/mst_chart.rb
class MstChart < ApplicationRecord
  belongs_to :mst_music

  enum difficulty: { other: 0, nov: 1, adv: 2, exh: 3, mxm: 4, inf: 5, grv: 6, hvn: 7, vvd: 8 }

  mount_uploader :jacket, ChartJacketUploader
end

app/models/mst_music.rb
class MstMusic < ApplicationRecord
  has_many :mid_music_music_genres, dependent: :destroy
  has_many :mst_music_genres, through: :mid_music_music_genres
  has_many :mst_charts, dependent: :destroy
end

app/models/mst_music_genre.rb
class MstMusicGenre < ApplicationRecord
  has_many :mid_music_music_genres, dependent: :destroy
  has_many :mst_musics, through: :mid_music_music_genres
end

app/models/tbl_player.rb
class TblPlayer < ApplicationRecord
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    before_action :basic_auth

    def basic_auth
      authenticate_or_request_with_http_basic do |username, password|
        username == 'komei' && password == 'hashimoto'
      end
    end
  end
end

app/controllers/admin/top_controller.rb
module Admin
  class TopController < Admin::BaseController
    def index; end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/front/base_controller.rb
module Front
  class BaseController < ApplicationController
    before_action :basic_auth

    def basic_auth
      authenticate_or_request_with_http_basic do |username, password|
        username == 'wanirou' && password == 'wanirou'
      end
    end
  end
end

app/controllers/front/top_controller.rb
module Front
  class TopController < Front::BaseController
    def index; end
  end
end

app/controllers/front/vf_rank_controller.rb
class Front::VfRankController < ApplicationController
  def index
    @tbl_players = TblPlayer.order(volforce_rank: :asc).page(params[:page]).per(50)
    @window_size = browser.device.mobile? ? 2 : 5
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = AppSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?

    handle_error_in_development e
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: :internal_server_error
  end
end

app/helpers/admin/top_helper.rb
module Admin
  module TopHelper
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front/top_helper.rb
module Front
  module TopHelper
  end
end

app/helpers/front/vf_rank_helper.rb
module Front::VfRankHelper
end

app/views/admin/top/index.html.erb
hoge

app/views/front/top/index.html.erb
<div class="uk-section uk-section-primary uk-preserve-color">
	<div class="uk-container">
		<div class="uk-panel uk-light uk-margin-medium">
			<h3>Contents</h3>
		</div>

		<div class="uk-grid-match uk-child-width-1-3@m" uk-grid>
			<div>
				<%= link_to vf_rank_path, class: 'uk-card uk-card-default uk-card-hover uk-card-body uk-link-toggle uk' do %>
					<h3>VOLFORCE Ranking <span uk-icon="icon: chevron-right"></span></h3>
					<p>IMPERIAL以上のVOLFORCEランキングです。</p>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/front/vf_rank/index.html.erb
<div class="uk-section uk-section-small">
  <div class="uk-container uk-container-xsmall">
    <h1 class="uk-heading-line uk-text-center"><span>VOLFORCE Ranking</span></h1>

    <div class="uk-section uk-section-xsmall">
      <table class="uk-table uk-table-small uk-table-middle uk-table-divider uk-table-hover">
        <thead>
          <tr>
            <th class="uk-table-shrink uk-text-center">RANK</th>
            <th class="uk-width-small uk-text-center">PLAYER NAME</th>
            <th class="uk-table-shrink uk-text-center">VOLFORCE</th>
          </tr>
        </thead>
        <tbody>
          <% @tbl_players.each do |tbl_player| %>
            <tr class="uk-text-center">
              <td><%= tbl_player.volforce_rank %></td>
              <td><%= tbl_player.name %></td>
              <td><%= sprintf("%#.05g", (tbl_player.volforce / 1000.0)) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <%= paginate @tbl_players, window: @window_size %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>